### ISSUE TITLE
Testgrid error: podinfo.json not found please install prow's gcs reporter

### ISSUE THREAD

**Issue by wallrj** [jetstack/testing#464]
All the testgrid reports are marked failed, with an error message:
```
podinfo.json not found please install prow's gcs reporter
```
https://testgrid.k8s.io/jetstack-cert-manager-master#ci-cert-manager-bazel

Maybe this is the reporter:
 * https://pkg.go.dev/k8s.io/test-infra/prow/crier/reporters/gcs
 * https://github.com/kubernetes/test-infra/blob/0101566d4ceb/prow/crier/reporters/gcs/reporter.go

But there is very little documentation in those files.

**Comment by irbekrm** [comment]
#465 would enable the reporter I hope.
