### ISSUE TITLE
Use Kubernetes 1.21

### ISSUE THREAD

**Issue by maelvls** [jetstack/testing#476]
Kubernetes 1.21 was released on Thu 8 April 2021. It would be nice if we could start testing this.

Related:
- https://github.com/cert-manager/website/pull/452

**Comment by irbekrm** [comment]
This can now be worked- kind image with k8s 1.21 has been published https://hub.docker.com/layers/kindest/node/v1.21.1/images/sha256-20fe57f336d001526607ff22ad95c126c6730ea9819881fa2777b1d4c9f6c230?context=explore

**Comment by maelvls** [comment]
Could we add 1.21 to our supported releases page "testing" [table](https://cert-manager.io/docs/installation/supported-releases/#kubernetes-supported-versions)? 👍

**Comment by irbekrm** [comment]
Related comment https://github.com/jetstack/cert-manager/pull/4029#issuecomment-844098188
