### ISSUE TITLE
Investigate why TestGrid config no longer gets generated.

### ISSUE THREAD

**Issue by irbekrm** [jetstack/testing#488]
Our TestGrid config is in `kubernetes/test-infra` repo [here](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/jetstack/gen-config.yaml).

We have some automation (need documentation) that re-generates the config and PRs in changes.

It seems to be broken- I have added a new ProwJob in #487 , but did not see a new PR against test-infra.

/kind bug

**Comment by munnerz** [comment]
https://github.com/kubernetes/test-infra/pull/21135 I _think_ it's working fine?

**Comment by munnerz** [comment]
https://github.com/kubernetes/test-infra/pull/21135/files#diff-b0bfe0cec506cbffbb3bdfdbe0e473eba906acd64752b5e653afeb59e1ed19ecR149

**Comment by munnerz** [comment]
A new PR is not created each time - if one already exists/is still open, it is reused 😄 

/close

**Comment by irbekrm** [comment]
Ah, I didn't realize it would update an old existing PR!
