### ISSUE TITLE
Test against Kubernetes v1.22

### ISSUE THREAD

**Issue by irbekrm** [jetstack/testing#519]
We would like `cert-manager` `v1.5` to be deployable on Kubernetes `v1.22`.

Because Kubernetes `v1.22` will be released shortly before `cert-manager` `v1.5`, there probably won't yet be a kind image, so we should build our own and start testing `cert-manager` master once it is usable with `v1.22` (https://github.com/jetstack/cert-manager/issues/3390).

**Comment by irbekrm** [comment]
Building the kind image seems straightforward:
1. Ensure there is k8s source repo at GOPATH with the desired tag checked out
2. Run `kind build node-image`

See https://kubernetes.slack.com/archives/CEKK1KTN2/p1618422131300800

**Comment by maelvls** [comment]
I successfully built `kindest/node:v1.22.0-rc.0`. Where can we push the image? I was thinking of

```
eu.gcr.io/jetstack-build-infra-images/kindest/node:v1.22.0-rc.0
```

But I don't have push write to this registry.

**Comment by irbekrm** [comment]
@maelvls  I am actually currently working on adding a CI workflow to push to build infra images.
Not sure if it's not an overkill, but alternatives would be either to manually push there which does not seem great or add to cert-manager repo a path to private Docker registry which also does not seem great.

**Comment by maelvls** [comment]
Your idea is way better! Never mind my comment. 😅

**Comment by irbekrm** [comment]
Yeah I think we need to document the image build workflow better as well (i.e the contents of https://github.com/jetstack/testing/tree/master/images )
